services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackcentral_backend
    ports:
      - "7777:7777"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackcentral_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: unless-stopped
