const EVENTS = [
  {
    id: 1,
    title: "Global AI & Generative Hack",
    date: "Oct 12 - 14, 2024",
    type: "Hackathon",
    typeColor: "bg-[#0d4af2]",
    mode: "Online",
    modeColor: "bg-emerald-500",
    tags: ["PyTorch", "OpenAI"],
    registered: "542",
    bgGradient: "from-indigo-600 via-blue-700 to-cyan-500",
  },
  {
    id: 2,
    title: "Advanced React Patterns",
    date: "Oct 15, 2024",
    type: "Workshop",
    typeColor: "bg-amber-500",
    mode: "In-Person",
    modeColor: "bg-[#0d4af2]",
    tags: ["React", "TypeScript"],
    registered: "120",
    bgGradient: "from-orange-500 via-rose-500 to-pink-600",
  },
  {
    id: 3,
    title: "Web3 World Build-a-thon",
    date: "Oct 20 - 22, 2024",
    type: "Hackathon",
    typeColor: "bg-[#0d4af2]",
    mode: "Online",
    modeColor: "bg-emerald-500",
    tags: ["Solidity", "Ethereum"],
    registered: "2.1k",
    bgGradient: "from-purple-600 via-violet-600 to-indigo-700",
  },
  {
    id: 4,
    title: "Cloud Native Summit 2024",
    date: "Oct 25, 2024",
    type: "Workshop",
    typeColor: "bg-amber-500",
    mode: "Hybrid",
    modeColor: "bg-[#0d4af2]",
    tags: ["Kubernetes", "Go"],
    registered: "890",
    bgGradient: "from-sky-500 via-blue-500 to-indigo-600",
  },
  {
    id: 5,
    title: "Securithon: Zero Trust",
    date: "Nov 02 - 04, 2024",
    type: "Hackathon",
    typeColor: "bg-[#0d4af2]",
    mode: "Online",
    modeColor: "bg-emerald-500",
    tags: ["C++", "Linux"],
    registered: "415",
    bgGradient: "from-red-600 via-rose-600 to-pink-700",
  },
  {
    id: 6,
    title: "Mobile First: Flutter Dev",
    date: "Nov 10 - 12, 2024",
    type: "Hackathon",
    typeColor: "bg-[#0d4af2]",
    mode: "In-Person",
    modeColor: "bg-[#0d4af2]",
    tags: ["Flutter", "Dart"],
    registered: "230",
    bgGradient: "from-teal-500 via-emerald-500 to-green-600",
  },
];

const CATEGORIES = [
  { icon: "code", label: "Development", active: true },
  { icon: "brush", label: "Design & UI", active: false },
  { icon: "psychology", label: "Artificial Intelligence", active: false },
];

const TECH_TAGS = ["React", "Python", "Rust", "Next.js", "Web3"];

export { EVENTS, CATEGORIES, TECH_TAGS };